# Generated by Django 4.1.3 on 2025-08-01 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("id_cliente", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=30)),
                ("apellidos", models.CharField(max_length=50)),
                ("direccion", models.CharField(max_length=30)),
                ("email", models.CharField(max_length=30)),
                ("telefono", models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                "db_table": "cat_cliente",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                ("id_producto", models.AutoField(primary_key=True, serialize=False)),
                ("producto", models.CharField(max_length=40)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
            ],
            options={
                "db_table": "cat_producto",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Venta",
            fields=[
                ("id_venta", models.AutoField(primary_key=True, serialize=False)),
                ("fecha", models.DateField(blank=True, null=True)),
                (
                    "id_cliente",
                    models.ForeignKey(
                        db_column="id_cliente",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="ventas.cliente",
                    ),
                ),
            ],
            options={
                "db_table": "tra_venta",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="VentaDetalle",
            fields=[
                ("id_venta_det", models.AutoField(primary_key=True, serialize=False)),
                ("cantidad", models.IntegerField()),
                (
                    "descuento",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "id_producto",
                    models.ForeignKey(
                        db_column="id_producto",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="ventas.producto",
                    ),
                ),
                (
                    "id_venta",
                    models.ForeignKey(
                        db_column="id_venta",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="ventas.venta",
                    ),
                ),
            ],
            options={
                "db_table": "tra_venta_det",
                "managed": True,
                "unique_together": {("id_venta", "id_producto")},
            },
        ),
    ]
