# Generated by Django 4.2.11 on 2026-08-12 19:59

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_ensure_schema_postgres'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdicionCurso',
            fields=[
                ('id_edicion', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_edicion', models.CharField(max_length=30, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('cupo_maximo', models.PositiveSmallIntegerField(default=20)),
                ('cupo_ocupado', models.PositiveSmallIntegerField(default=0)),
                ('precio_edicion', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('en_curso', 'En curso'), ('cerrada', 'Cerrada')], default='programada', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ediciones', to='ventas.curso')),
            ],
            options={
                'db_table': 'cat_edicion_curso',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_alumno_sii',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='notas',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='comision_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='venta',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('pagado', 'Pagado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='folio',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=4, max_digits=19)),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('credito', 'Crédito')], default='transferencia', max_length=20)),
                ('referencia', models.CharField(blank=True, default='', max_length=60)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aplicado', 'Aplicado'), ('rechazado', 'Rechazado')], default='aplicado', max_length=20)),
                ('id_venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pago_set', to='ventas.venta')),
            ],
            options={
                'db_table': 'tra_pago',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id_inscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='activa', max_length=20)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('id_alumno_externo', models.IntegerField(blank=True, null=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, related_name='inscripciones', to='ventas.cliente')),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.DO_NOTHING, related_name='inscripciones', to='ventas.curso')),
                ('id_edicion', models.ForeignKey(blank=True, db_column='id_edicion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inscripciones', to='ventas.edicioncurso')),
                ('id_venta_det', models.ForeignKey(blank=True, db_column='id_venta_det', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inscripciones', to='ventas.ventadetalle')),
            ],
            options={
                'db_table': 'tra_inscripcion',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='ventadetalle',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='id_edicion',
            field=models.ForeignKey(blank=True, db_column='id_edicion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ventas_detalle', to='ventas.edicioncurso'),
        ),
        migrations.AlterUniqueTogether(
            name='ventadetalle',
            unique_together={('id_venta', 'id_curso', 'id_edicion')},
        ),
    ]
